export const SENSITIVE_TOPIC_OPTIONS: { value: string; label: string }[] = [
  { value: 'physical-abuse', label: 'Physical abuse' },
  { value: 'emotional-abuse', label: 'Emotional abuse' },
  { value: 'sexual-abuse', label: 'Sexual abuse' },
  { value: 'neglect', label: 'Neglect' },
  { value: 'bullying', label: 'Bullying' },
  { value: 'loss-grief', label: 'Loss / grief' },
  { value: 'addiction', label: 'Addiction' },
  { value: 'disordered-eating', label: 'Disordered eating' },
  { value: 'self-harm-history', label: 'Self-harm history' },
  { value: 'gender-identity-dysphoria', label: 'Gender identity / dysphoria' },
  { value: 'coming-out', label: 'Coming out' },
  { value: 'family-rejection', label: 'Family rejection' },
  { value: 'identity-discrimination', label: 'Identity-based discrimination' },
  { value: 'prefer-not-to-say', label: 'Prefer not to say' },
  { value: 'none', label: 'None of these' },
];
