'use client';

import { SharedReport, CheckIn } from '@/lib/supabase';
import { GaugeChart } from './GaugeChart';
import { TrendChart } from './TrendChart';

interface Props {
  report: SharedReport;
  checkins: CheckIn[];
}

const GAUGE_LABELS: Record<string, string> = {
  body: 'Body',
  state: 'State',
  emotion: 'Emotion',
  connection: 'Connection',
  direction: 'Direction',
  alignment: 'Alignment',
};

const GAUGE_COLORS: Record<string, string> = {
  body: '#F59E0B',
  state: '#10B981',
  emotion: '#EC4899',
  connection: '#8B5CF6',
  direction: '#3B82F6',
  alignment: '#06B6D4',
};

function computeAverages(checkins: CheckIn[]) {
  const gauges = ['body', 'state', 'emotion', 'connection', 'direction', 'alignment'] as const;
  const result: Record<string, number> = {};
  
  for (const gauge of gauges) {
    const values = checkins.map(c => c[gauge]).filter((v): v is number => v != null);
    if (values.length) {
      result[gauge] = Math.round(values.reduce((a, b) => a + b, 0) / values.length);
    }
  }
  return result;
}

function computeTrend(checkins: CheckIn[], gauge: string): 'up' | 'down' | 'stable' | null {
  if (checkins.length < 4) return null;
  const mid = Math.floor(checkins.length / 2);
  const first = checkins.slice(0, mid);
  const second = checkins.slice(mid);
  
  const getAvg = (data: CheckIn[]) => {
    const values = data.map(c => c[gauge as keyof CheckIn]).filter((v): v is number => typeof v === 'number');
    return values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0;
  };
  
  const diff = getAvg(second) - getAvg(first);
  if (diff > 5) return 'up';
  if (diff < -5) return 'down';
  return 'stable';
}

export function ReportViewer({ report, checkins }: Props) {
  const { config } = report;
  const averages = computeAverages(checkins);
  const gaugeKeys = Object.keys(averages);
  
  const formatDate = (iso: string) => new Date(iso).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });

  return (
    <main className="report-container">
      {/* Header */}
      <header className="mb-8 pb-6 border-b border-gray-200 dark:border-gray-700">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 bg-brand-500 rounded-xl flex items-center justify-center">
            <span className="text-white font-bold text-lg">iG</span>
          </div>
          <div>
            <h1 className="text-xl font-semibold text-gray-900 dark:text-white">
              Wellness Report
            </h1>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Generated by InGauge
            </p>
          </div>
        </div>
        
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
          {config.patientIdentifier && (
            <div>
              <span className="text-gray-500 dark:text-gray-400">Client:</span>{' '}
              <span className="text-gray-900 dark:text-white font-medium">
                {config.patientIdentifier}
              </span>
            </div>
          )}
          {config.recipientInfo?.name && (
            <div>
              <span className="text-gray-500 dark:text-gray-400">For:</span>{' '}
              <span className="text-gray-900 dark:text-white font-medium">
                {config.recipientInfo.name}
                {config.recipientInfo.title && `, ${config.recipientInfo.title}`}
              </span>
            </div>
          )}
          <div>
            <span className="text-gray-500 dark:text-gray-400">Period:</span>{' '}
            <span className="text-gray-900 dark:text-white font-medium">
              {formatDate(config.timeRange.start)} – {formatDate(config.timeRange.end)}
            </span>
          </div>
          <div>
            <span className="text-gray-500 dark:text-gray-400">Check-ins:</span>{' '}
            <span className="text-gray-900 dark:text-white font-medium">
              {checkins.length}
            </span>
          </div>
        </div>
      </header>

      {/* Executive Summary */}
      {config.sections.executiveSummary && (
        <section className="mb-8">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
            Summary
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
            {gaugeKeys.map(gauge => {
              const trend = computeTrend(checkins, gauge);
              return (
                <div key={gauge} className="gauge-card text-center">
                  <div
                    className="gauge-value"
                    style={{ color: GAUGE_COLORS[gauge] }}
                  >
                    {averages[gauge]}
                  </div>
                  <div className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                    {GAUGE_LABELS[gauge]}
                  </div>
                  {trend && (
                    <div className="text-xs mt-2">
                      {trend === 'up' && <span className="text-green-600">↑ Improving</span>}
                      {trend === 'down' && <span className="text-red-600">↓ Declining</span>}
                      {trend === 'stable' && <span className="text-gray-500">→ Stable</span>}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </section>
      )}

      {/* Gauge Trends */}
      {config.sections.gaugeTrends && checkins.length >= 2 && (
        <section className="mb-8">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
            Trends Over Time
          </h2>
          <div className="gauge-card">
            <TrendChart checkins={checkins} />
          </div>
        </section>
      )}

      {/* Footer */}
      <footer className="mt-12 pt-6 border-t border-gray-200 dark:border-gray-700 text-center text-sm text-gray-500 dark:text-gray-400">
        <p>This report was generated at the request of the InGauge user.</p>
        <p className="mt-1">
          Data reflects self-reported wellness check-ins and should be interpreted in context.
        </p>
        <p className="mt-4 text-xs">
          Report ID: {report.short_code} • Expires: {formatDate(report.expires_at)}
        </p>
      </footer>
    </main>
  );
}
