/**
 * Legal & safety disclaimer copy for InGauge.
 * Single source of truth for platform protection (Headspace/Calm/Oura style).
 */

import { APP_CONFIG } from '../lib/constants';

const APP_NAME = APP_CONFIG.name;

/** Global app disclaimer — always accessible in footer/settings */
export const GLOBAL_DISCLAIMER = {
  short: `${APP_NAME} provides AI-assisted tools for self-reflection, education, and personal development. It does not provide medical, psychological, legal, or financial advice.`,
  full: `${APP_NAME} provides AI-assisted tools for self-reflection, education, and personal development.\n\n` +
    `The app does not provide medical, psychological, legal, or financial advice. Any insights, suggestions, or simulations generated by the AI are informational only and should not replace professional guidance from licensed experts.\n\n` +
    `If you are experiencing serious emotional distress or a mental health crisis, please contact a licensed professional or emergency services.`,
  learnMoreLabel: 'Learn more',
};

/** Shown before first AI interaction */
export const AI_DISCLAIMER = {
  title: 'AI Guidance Notice',
  body: 'Responses are generated by artificial intelligence and may not always be accurate or appropriate. Use AI insights as reflection tools rather than professional advice.',
  button: 'I understand',
};

/** Mental health boundary — not therapy */
export const MENTAL_HEALTH_BOUNDARY = {
  short: `${APP_NAME} is not a therapy or counseling service and does not diagnose or treat mental health conditions.`,
  full: `${APP_NAME} is not a therapy or counseling service and does not diagnose or treat mental health conditions. ` +
    `The platform is designed for self-reflection and personal growth, not crisis intervention or emergency situations. ` +
    `For mental health care, please consult a licensed professional.`,
};

/** Voice recording disclosure — before voice features */
export const VOICE_DISCLOSURE = {
  title: 'Voice Interaction Notice',
  body: 'When you use voice features, your speech may be processed to convert audio into text and generate AI responses. Audio may be temporarily processed to improve the experience. You can control voice storage in Settings > Privacy.',
  button: 'I understand',
};

/** Safety / crisis notice */
export const SAFETY_NOTICE = {
  short: `${APP_NAME} is designed for self-reflection and personal growth. It is not intended for crisis intervention or emergency situations.`,
  crisisResources: '988 Suicide & Crisis Lifeline (call or text 988)\nCrisis Text Line (text HOME to 741741)\n\nThese resources are free and available 24/7.',
};

/** Educational content (Manual / learning modules) */
export const EDUCATIONAL_DISCLAIMER = 'Educational materials within ' + APP_NAME + ' are intended for informational purposes only and do not replace professional advice.';

/** Roleplay / simulation */
export const SIMULATION_DISCLAIMER = 'Conversation simulations are AI-generated practice environments and may not represent real human responses.';

/** Pattern detection / AI insights */
export const PATTERN_DISCLAIMER = 'Insights generated by the app are algorithmic interpretations and may not fully represent real-world circumstances.';

/** Age requirement */
export const AGE_REQUIREMENT = {
  minimumAge: 13,
  statement: 'You must be at least 13 years old to use ' + APP_NAME + '.',
  checkboxLabel: 'I confirm I am at least 13 years old.',
};

/** AI training disclosure */
export const AI_TRAINING_DISCLOSURE = {
  label: 'Allow AI learning',
  hint: 'Your conversations may be used to improve the AI system unless you disable this in Settings.',
  disableLabel: 'Disable AI learning',
};

/** Data use categories for "How Your Data Is Used" */
export const DATA_USE_SECTIONS = [
  {
    title: 'Data you provide',
    items: ['Profile information (name, preferences)', 'Journal entries and reflections', 'Answers to check-ins and life questions', 'Voice recordings (if you use voice features)'],
  },
  {
    title: 'Data generated by AI',
    items: ['Conversation summaries', 'Insights and pattern detection', 'Suggested actions and reflections'],
  },
  {
    title: 'Data from integrations',
    items: ['If you connect Apple Health: sleep, activity, heart rate (used for Body gauge only)', 'No data is sold or used for advertising'],
  },
];

/** Privacy dashboard copy */
export const PRIVACY_DASHBOARD = {
  title: 'Privacy & Data',
  voiceStorage: 'Store voice transcripts',
  voiceStorageHint: 'Keep transcripts of voice input for your history. You can delete them anytime.',
  aiLearning: 'Allow AI learning',
  aiLearningHint: 'Let the app use anonymized patterns to improve AI (you can disable this).',
  downloadData: 'Download my data',
  downloadDataHint: 'Export your data (GDPR/CCPA friendly).',
  deleteData: 'Delete my data',
  deleteDataHint: 'Permanently remove your account and all stored data.',
};

/** Security statement */
export const SECURITY_STATEMENT = APP_NAME + ' uses industry-standard security measures to protect your data.';

/** Research transparency — educational content credibility */
export const RESEARCH_TRANSPARENCY =
  'Educational content in ' + APP_NAME + ' is based on widely accepted research in psychology and behavioral science. It is intended for learning and reflection, not diagnosis or treatment.';

/** Full AI disclosure (for Legal / AI Disclosure page or section) */
export const AI_DISCLOSURE_FULL = {
  title: 'AI Disclosure',
  intro: 'You have the right to know when you are interacting with artificial intelligence.',
  points: [
    'Responses from Gauge and other in-app AI features are generated by artificial intelligence, not by a human.',
    'AI may not always be accurate or appropriate. Use insights as reflection tools, not professional advice.',
    'We do not design the AI to deceive you. You should never be led to believe you are talking to a licensed professional or a human when you are not.',
    'You can report problems or send feedback anytime via Me → Send Feedback or Help Center.',
  ],
};

/** Short safety guidelines (human oversight, reporting) */
export const SAFETY_GUIDELINES = {
  title: 'Safety & support',
  report: 'You can report problems or contact support anytime: Me → Send Feedback, or Help Center (docs.getingauge.com).',
  crisis: 'If you are in crisis, use 988 or Crisis Text Line (741741). This app is not for emergency intervention.',
};

/** Data minimization — one-line for privacy policy / data use */
export const DATA_MINIMIZATION_NOTE =
  APP_NAME + ' collects only what is needed to provide the service (e.g. profile, reflections, optional voice). We do not collect location for tracking, and we do not sell or use your data for advertising.';
